rm hw6
rm o_puzzle_sample.txt
rm o_puzzle_sample_all.txt
rm o_puzzle_sample_constraints.txt
rm o_puzzle_sample_constraints_all.txt
rm o_puzzle_sample_unknowns.txt
rm o_puzzle_sample_unknowns_all.txt
rm o_puzzle1.txt
rm o_puzzle1_all.txt
rm o_puzzle2.txt
rm o_puzzle2_all.txt
rm o_puzzle3.txt
rm o_puzzle3_all.txt
rm o_puzzle4.txt
rm o_puzzle4_all.txt
rm o_puzzle4_unknowns.txt
rm o_puzzle4_unknowns_all.txt
rm o_puzzle5.txt
rm o_puzzle5_all.txt
rm o_puzzle6.txt
rm o_puzzle6_all.txt
rm o_puzzle6_unknowns.txt
rm o_puzzle6_unknowns_all.txt
rm o_puzzle7.txt
rm o_puzzle7_all.txt
rm o_puzzle8.txt
rm o_puzzle8_all.txt
rm o_puzzle9.txt
rm o_puzzle9_all.txt
rm o_puzzle9_constraints.txt
rm o_puzzle9_constraints_all.txt
rm o_puzzle10.txt
rm o_puzzle10_all.txt
rm o_puzzle10_constraints.txt
rm o_puzzle10_constraints_all.txt
